# Schema for the configuration files of the Entity version history module.

entity_version_history.settings.*.*:
  type: config_entity
  label: 'Entity Version History Settings'
  mapping:
    id:
      type: string
      label: 'ID'
    target_entity_type_id:
      type: string
      label: 'Entity Type ID'
    target_bundle:
      type:  string
      label: 'Bundle'
    target_field:
      type: string
      label: 'Target field'
