<?php

/**
 * @file
 * Entity version workflows module.
 */

declare(strict_types = 1);

use Drupal\Core\Entity\ContentEntityInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\workflows\WorkflowInterface;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function entity_version_workflows_form_workflow_type_edit_form_alter(&$form, FormStateInterface $form_state) {
  $form['#submit'][] = '_entity_version_workflows_workflow_type_submit';
}

/**
 * Implements hook_form_alter().
 */
function entity_version_workflows_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if ($form_id === 'workflow_transition_add_form' || $form_id === 'workflow_transition_edit_form') {
    _entity_version_workflows_alter_transition_forms($form, $form_state, $form_id);
  }
}

/**
 * Handles the form alter for the workflow transition add/edit forms.
 *
 * @param object $form
 *   The form object.
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 *   The form state object.
 * @param string $form_id
 *   The ID of the form.
 */
function _entity_version_workflows_alter_transition_forms(&$form, FormStateInterface $form_state, $form_id): void {
  $workflow = $form_state->getFormObject()->getEntity();
  $values = $workflow->getThirdPartySetting('entity_version_workflows', $form['id']['#value']);

  $form['version'] = [
    '#type' => 'details',
    '#title' => t('Version control'),
    '#description' => t('Select what should happen to the version number when this transition is used.'),
    '#open' => TRUE,
  ];

  $form['version']['major'] = [
    '#type' => 'select',
    '#title' => t('Major'),
    '#default_value' => $values ? $values['major'] : '',
    '#options' => [
      '' => t('Nothing'),
      'increase' => t('Increase'),
      'decrease' => t('Decrease'),
      'reset' => t('Reset'),
    ],
    '#required' => FALSE,
  ];

  $form['version']['minor'] = [
    '#type' => 'select',
    '#title' => t('Minor'),
    '#default_value' => $values ? $values['minor'] : '',
    '#options' => [
      '' => t('Nothing'),
      'increase' => t('Increase'),
      'decrease' => t('Decrease'),
      'reset' => t('Reset'),
    ],
    '#required' => FALSE,
  ];

  $form['version']['patch'] = [
    '#type' => 'select',
    '#title' => t('Patch'),
    '#default_value' => $values ? $values['patch'] : '',
    '#options' => [
      '' => t('Nothing'),
      'increase' => t('Increase'),
      'decrease' => t('Decrease'),
      'reset' => t('Reset'),
    ],
    '#required' => FALSE,
  ];

  $form['#entity_builders'][] = '_entity_version_workflows_form_transition_add_form_builder';
}

/**
 * Entity builder for the transition configuration entity.
 *
 * @param string $entity_type
 *   The type of the entity.
 * @param \Drupal\workflows\WorkflowInterface $workflow
 *   The transition object.
 * @param object $form
 *   The form object.
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 *   The form state object.
 */
function _entity_version_workflows_form_transition_add_form_builder($entity_type, WorkflowInterface $workflow, &$form, FormStateInterface $form_state): void {
  $version_fields = [
    'major',
    'minor',
    'patch',
  ];
  $values = [];

  foreach ($version_fields as $field) {
    if ($form_state->getValue($field)) {
      $values[$field] = $form_state->getValue($field);
    }
  }

  if ($values) {
    $workflow->setThirdPartySetting('entity_version_workflows', $form_state->getValue('id'), $values);
    return;
  }
  $workflow->unsetThirdPartySetting('entity_version_workflows', $form_state->getValue('id'));
}

/**
 * Implements hook_entity_presave().
 */
function entity_version_workflows_entity_presave(EntityInterface $entity) {
  // Catch the node entity and update the entity version field.
  if (!($entity instanceof ContentEntityInterface)) {
    return;
  }

  $bundle_fields = \Drupal::service('entity_field.manager')->getFieldDefinitions($entity->getEntityTypeId(), $entity->bundle());
  foreach ($bundle_fields as $field) {
    /** @var \Drupal\field\Entity\FieldConfig $field */
    if ($field->getType() === 'entity_version') {
      /** @var \Drupal\entity_version_workflows\Services\EntityVersionWorkflowManager $entity_version_manager */
      $entity_version_handler = \Drupal::service('entity_version_workflows.entity_version_workflow_manager');
      $entity_version_handler->updateEntityVersion($entity, $field->getName());
      break;
    }
  }
}
