<?php

/**
 * @file
 * Entity version history module.
 */

declare(strict_types = 1);

/**
 * Implements hook_entity_type_alter().
 */
function entity_version_history_entity_type_alter(array &$entity_types) {
  /* @var $config_factory \Drupal\Core\Config\ConfigFactory */
  $config_factory = \Drupal::configFactory();
  // To avoid infinite loop we use config factory to load all configs.
  $configs = $config_factory->listAll('entity_version.settings');

  if (empty($configs)) {
    return;
  }

  $configs = $config_factory->loadMultiple($configs);

  foreach ($configs as $config) {
    $entity_type = $config->get('target_entity_type_id');

    if (!$entity_types[$entity_type]->getLinkTemplate('canonical')) {
      return;
    }

    $history_path = $entity_types[$entity_type]->getLinkTemplate('canonical') . '/history';
    $entity_types[$entity_type]->setLinkTemplate('entity-version-history', $history_path);
  }
}
