<?php

/**
 * @file
 * Install and update functions for the Entity Version History module.
 */

declare(strict_types = 1);

/**
 * Implements hook_uninstall().
 */
function entity_version_history_uninstall() {
  // Remove the existing config entities.
  $storage = \Drupal::entityTypeManager()->getStorage('entity_version_history_settings');
  $configs = $storage->loadMultiple();
  $storage->delete($configs);
}
